### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by amandalmia14** [5hirish/adam_qas#22]
When I try to run the qas.adam, it gives me the following errors. 

(venv) admin@BLR:~/aman/experiments/adam_qas$ python -m qas.adam "When was linux kernel version 4.0 released ?"
I think what you want to know is: When was linux kernel version 4.0 released ?
Traceback (most recent call last):
  File "/home/administrator/aman/experiments/adam_qas/venv/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/administrator/aman/experiments/adam_qas/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/administrator/aman/experiments/adam_qas/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/administrator/aman/experiments/adam_qas/venv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 166, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=request_headers, **kw)
  File "/home/administrator/aman/experiments/adam_qas/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/administrator/aman/experiments/adam_qas/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/administrator/aman/experiments/adam_qas/venv/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/administrator/aman/experiments/adam_qas/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/administrator/aman/experiments/adam_qas/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/administrator/aman/experiments/adam_qas/venv/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/administrator/aman/experiments/adam_qas/venv/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fe75d441e10>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/administrator/aman/experiments/adam_qas/qas/adam.py", line 273, in <module>
    run()
  File "/home/administrator/aman/experiments/adam_qas/qas/adam.py", line 269, in run
    main(sys.argv[1:])
  File "/home/administrator/aman/experiments/adam_qas/qas/adam.py", line 262, in main
    answer = qas.process_answer()
  File "/home/administrator/aman/experiments/adam_qas/qas/adam.py", line 108, in process_answer
    search_wikipedia(self.question_keywords, self.search_depth)
  File "/home/administrator/aman/experiments/adam_qas/qas/wiki/wiki_search.py", line 21, in search_wikipedia
    wikif = WikiFetch(wiki_page_ids)
  File "/home/administrator/aman/experiments/adam_qas/qas/wiki/wiki_fetch.py", line 37, in __init__
    self.es_ops = ElasticSearchOperate()
  File "/home/administrator/aman/experiments/adam_qas/qas/esstore/es_operate.py", line 24, in __init__
    es = ElasticSearchConn()
  File "/home/administrator/aman/experiments/adam_qas/qas/esstore/es_connect.py", line 18, in __call__
    cls._instances[cls] = super(ElasticSearchMeta, cls).__call__(*args, **kwargs)
  File "/home/administrator/aman/experiments/adam_qas/qas/esstore/es_connect.py", line 31, in __init__
    self.set_up_index()
  File "/home/administrator/aman/experiments/adam_qas/qas/esstore/es_connect.py", line 121, in set_up_index
    index_exists = self.__es_conn__.indices.exists(index=__index_name__)
  File "/home/administrator/aman/experiments/adam_qas/venv/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/administrator/aman/experiments/adam_qas/venv/lib/python3.6/site-packages/elasticsearch/client/indices.py", line 213, in exists
    params=params)
  File "/home/administrator/aman/experiments/adam_qas/venv/lib/python3.6/site-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/home/administrator/aman/experiments/adam_qas/venv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 175, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7fe75d441e10>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fe75d441e10>: Failed to establish a new connection: [Errno 111] Connection refused)

## Your Environment

* Operating System: Linux
* Python Version Used: 3.6.3

**Comment by 5hirish** [comment]
@amandalmia14 I suspect you have not installed Elasticsearch 6.X, this project requires Elasticsearch to store the data extracted from Wikipedia. For installation instructions follow this [guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/_installation.html).

**Comment by amandalmia14** [comment]
My bad, I did installed elastic search. 
**I have two putty sessions running, in one elastic-search is running,**
[2018-05-03T15:14:04,619][INFO ][o.e.n.Node               ] [ArZSARQ] started
[2018-05-03T15:14:04,761][INFO ][o.e.g.GatewayService     ] [ArZSARQ] recovered [1] indices into cluster_state
[2018-05-03T15:14:05,085][INFO ][o.e.c.r.a.AllocationService] [ArZSARQ] Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[adam_qas][0]] ...]).

**and in another when I try to execute the python command, its gives an error.** 
I think what you want to know is: When was linux kernel version 4.0 released ?
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/administrator/aman/experiments/adam_qas/qas/adam.py", line 273, in <module>
    run()
  File "/home/administrator/aman/experiments/adam_qas/qas/adam.py", line 269, in run
    main(sys.argv[1:])
  File "/home/administrator/aman/experiments/adam_qas/qas/adam.py", line 262, in main
    answer = qas.process_answer()
  File "/home/administrator/aman/experiments/adam_qas/qas/adam.py", line 108, in process_answer
    search_wikipedia(self.question_keywords, self.search_depth)
  File "/home/administrator/aman/experiments/adam_qas/qas/wiki/wiki_search.py", line 22, in search_wikipedia
    wikif.parse_wiki_page()
  File "/home/administrator/aman/experiments/adam_qas/qas/wiki/wiki_fetch.py", line 51, in parse_wiki_page
    res = self.es_ops.upsert_wiki_article_if_updated(page, wiki_revid, wiki_title, wiki_html_text)
  File "/home/administrator/aman/experiments/adam_qas/qas/esstore/es_operate.py", line 83, in upsert_wiki_article_if_updated
    res = self.es_conn.update(index=__index_name__, doc_type=__doc_type__, body=wiki_body, id=pageid)
  File "/home/administrator/aman/experiments/adam_qas/venv/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/administrator/aman/experiments/adam_qas/venv/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 547, in update
    doc_type, id, '_update'), params=params, body=body)
  File "/home/administrator/aman/experiments/adam_qas/venv/lib/python3.6/site-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/home/administrator/aman/experiments/adam_qas/venv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 180, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/administrator/aman/experiments/adam_qas/venv/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', '[ArZSARQ][127.0.0.1:9300][indices:data/write/update[s]]')

Thanks.

**Comment by 5hirish** [comment]
@amandalmia14  Could run it in verbose mode and post the terminal output here:
`$ python -m qas.adam -vv "When was linux kernel version 4.0 released ?`
