### ISSUE TITLE
Running same query twice is causing error. 

### ISSUE THREAD

**Issue by amandalmia14** [5hirish/adam_qas#25]
## Your Environment

* Operating System: Windows
* Python Version Used: 3.6.3
* Elasticsearch Version Used 6.2.4:
* adam_qas Version Used: Latest
* Environment Information: 
* Question you were trying to ask:

When I run the -- `python -m qas.adam -vv "When was linux kernel version 4.0 released ?"` first time, I used to get answers perfectly. 
But when I run the **same** query again it give errors. 

```
Traceback (most recent call last):
  File "C:\Users\BLR\AppData\Local\Programs\Python\Python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\BLR\AppData\Local\Programs\Python\Python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\home\Aman Dalmia\Experiments\testing\adam_qas\qas\adam.py", line 273, in <module>
    run()
  File "D:\home\Aman Dalmia\Experiments\testing\adam_qas\qas\adam.py", line 269, in run
    main(sys.argv[1:])
  File "D:\home\Aman Dalmia\Experiments\testing\adam_qas\qas\adam.py", line 262, in main
    answer = qas.process_answer()
  File "D:\home\Aman Dalmia\Experiments\testing\adam_qas\qas\adam.py", line 108, in process_answer
    search_wikipedia(self.question_keywords, self.search_depth)
  File "D:\home\Aman Dalmia\Experiments\testing\adam_qas\qas\wiki\wiki_search.py", line 22, in search_wikipedia
    wikif.parse_wiki_page()
  File "D:\home\Aman Dalmia\Experiments\testing\adam_qas\qas\wiki\wiki_fetch.py", line 51, in parse_wiki_page
    res = self.es_ops.upsert_wiki_article_if_updated(page, wiki_revid, wiki_title, wiki_html_text)
  File "D:\home\Aman Dalmia\Experiments\testing\adam_qas\qas\esstore\es_operate.py", line 83, in upsert_wiki_article_if_updated
    res = self.es_conn.update(index=__index_name__, doc_type=__doc_type__, body=wiki_body, id=pageid)
  File "D:\home\AMANDA~1\EXPERI~1\testing\venv\lib\site-packages\elasticsearch\client\utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "D:\home\AMANDA~1\EXPERI~1\testing\venv\lib\site-packages\elasticsearch\client\__init__.py", line 547, in update
    doc_type, id, '_update'), params=params, body=body)
  File "D:\home\AMANDA~1\EXPERI~1\testing\venv\lib\site-packages\elasticsearch\transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=time
out)
  File "D:\home\AMANDA~1\EXPERI~1\testing\venv\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 180, in perform_reques
t
    self._raise_error(response.status, raw_data)
  File "D:\home\AMANDA~1\EXPERI~1\testing\venv\lib\site-packages\elasticsearch\connection\base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', '[jTr5AMq][127.0.0.1:9300][indices:data/write/
update[s]]')

```

**Comment by amandalmia14** [comment]
Apologies for the delay, below is the output of the above mentioned command. 

{
  "adam_qas" : {
    "mappings" : {
      "article" : {
        "_meta" : {
          "version" : 2
        },
        "properties" : {
          "content" : {
            "type" : "text",
            "analyzer" : "english"
          },
          "content_info" : {
            "type" : "text",
            "analyzer" : "english"
          },
          "content_table" : {
            "type" : "text",
            "analyzer" : "english"
          },
          "raw" : {
            "type" : "object",
            "enabled" : false
          },
          "revision" : {
            "type" : "long"
          },
          "title" : {
            "type" : "text",
            "analyzer" : "english"
          },
          "updated" : {
            "type" : "date"
          }
        }
      }
    }
  }
}

**Comment by 5hirish** [comment]
Fixed this issue, you will have to delete your old index, if you want the data to persist, you will have to reindex it. Read more [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html). 
To delete the old index:
`curl -X DELETE http://localhost:9200/adam_qas`
