### ISSUE TITLE
No module named 'dill.dill'

### ISSUE THREAD

**Issue by adrian410** [5hirish/adam_qas#28]
When i try to run your project i got this error :
(My friend tried also on a different PC on ubuntu and he got the same error )

```
adrian:~/Worskpace/adam_qas$ python3 -m qas.adam -vv "When was linux kernel version 4.0 released ?"

[2018-07-02 22:52:44] DEBUG:__main__:Thinking...
I think what you want to know is: When was linux kernel version 4.0 released ?
[2018-07-02 22:52:57] DEBUG:qas.classifier.question_classifier:WH : When | WH-POS : WRB | WH-NBOR-POS : VBD | Root-POS : VBN
[2018-07-02 22:52:57] DEBUG:qas.classifier.question_classifier:Union Columns: 63
[2018-07-02 22:52:57] DEBUG:qas.classifier.question_classifier:Training data: (5365, 63)
[2018-07-02 22:52:57] DEBUG:qas.classifier.question_classifier:Target data: (1, 63)
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/adrian/Worskpace/adam_qas/qas/adam.py", line 286, in <module>
    run()
  File "/home/adrian/Worskpace/adam_qas/qas/adam.py", line 282, in run
    main(sys.argv[1:])
  File "/home/adrian/Worskpace/adam_qas/qas/adam.py", line 274, in main
    qas.process_question()
  File "/home/adrian/Worskpace/adam_qas/qas/adam.py", line 106, in process_question
    self.question_class = classify_question(self.question_doc)
  File "/home/adrian/Worskpace/adam_qas/qas/classifier/question_classifier.py", line 164, in classify_question
    question_clf = load_classifier_model()
  File "/home/adrian/Worskpace/adam_qas/qas/classifier/question_classifier.py", line 96, in load_classifier_model
    return joblib.load(training_model_path)
  File "/home/adrian/Worskpace/adam_qas/virtualenv/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 578, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/adrian/Worskpace/adam_qas/virtualenv/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 508, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python3.5/pickle.py", line 1039, in load
    dispatch[key[0]](self)
  File "/usr/lib/python3.5/pickle.py", line 1334, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python3.5/pickle.py", line 1384, in find_class
    __import__(module, level=0)
ImportError: No module named 'dill.dill'
```
Can't figure out why i got this.

Result of pip freeze : 

```
boto==2.48.0
boto3==1.7.48
botocore==1.10.48
bz2file==0.98
certifi==2018.4.16
chardet==3.0.4
cymem==1.31.2
cytoolz==0.8.2
dill==0.2.8.2
docutils==0.14
elasticsearch==6.3.0
en-core-web-md==2.0.0
en-core-web-sm==2.0.0
gensim==3.4.0
idna==2.7
jmespath==0.9.3
lxml==4.2.3
msgpack-numpy==0.4.1
msgpack-python==0.5.6
murmurhash==0.28.0
numpy==1.14.5
pandas==0.23.1
pathlib==1.0.1
pkg-resources==0.0.0
plac==0.9.6
preshed==1.0.0
python-dateutil==2.7.3
pytz==2018.5
regex==2017.4.5
requests==2.19.1
s3transfer==0.1.13
scikit-learn==0.19.1
scipy==1.1.0
six==1.11.0
smart-open==1.6.0
spacy==2.0.11
termcolor==1.1.0
thinc==6.10.2
toolz==0.9.0
tqdm==4.23.4
ujson==1.35
urllib3==1.23
wrapt==1.10.11
```

```
python --version
Python 3.5.2
```

Does anyone have the same issue ?

**Comment by 5hirish** [comment]
Yeah, last two Travis builds failed due to this error. Will look into this issue.

**Comment by 5hirish** [comment]
Issue fixed.

**Comment by ArzaEshita** [comment]
I am getting the same error

**Comment by 5hirish** [comment]
@ArzaEshita can please provide me some stack trace or any other relevant information? Also, try once building from `master` again since I had frozen the dependencies yesterday, which might be causing this issue.

**Comment by ArzaEshita** [comment]
@5hirish I installed dill using 'pip install dill' and ran the code again. I didn't get the 'No module named 'dill.dil' error.
